name: ESLint Check

on: [workflow_dispatch, push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install dependencies
        working-directory: .
        run: pnpm i

      - name: Run Lint
        run: pnpm lint --no-fix
